name: "SSL Proxy"
description: "SSL-terminating reverse proxy for HTTP services"
version: "1.0.0"
slug: "ssl-proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
ports:
  8443/tcp: 8443
ports_description:
  8443/tcp: "SSL Proxy Port"
options:
  services:
    - name: "unraid"
      target_host: "192.168.178.93"
      target_port: 80
      ssl_port: 8443
      domain: "unraid.local"
      remove_csp: true
      websocket_support: true
schema:
  services:
    - name: str
      target_host: str
      target_port: int
      ssl_port: int
      domain: str
      remove_csp: bool?
      websocket_support: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
